use_frameworks!

platform :ios, '9.0'

target 'WhiteboardTools_Example' do
  pod 'WhiteboardTools', :path => '../'
  pod 'Masonry'
  pod 'NETURLSchemeHandler'
  pod 'SSZipArchive'
  pod 'Whiteboard'

  target 'WhiteboardTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
